#pragma once

/**
 * Movian Dedicated PlayStation 3 Configuration Header
 * Replaces dynamic configure script output with static, optimized definitions.
 */

#define PLATFORM "ps3"
#define PLATFORM_PS3 1
#define CONFIGURE_ARGS "ps3dev-monolithic"
#define APPNAME "movian"
#define APPNAMEUSER "Movian Next"
#define APPID "HTSS00004"

/* Defunct network endpoints neutralized */
#define PLUGINREPO ""
#define SHOWTIME_DEFAULT_UI "glw"
#define SHOWTIME_DEFAULT_LOGTARGET ""
#define SHOWTIME_GLW_DEFAULT_SKIN "flat"

#define ENABLE_AIRPLAY 0
#define CONFIG_AUDIOTEST 1
#define ENABLE_AUDIOTEST 1
#define ENABLE_AVAHI 0
#define CONFIG_BITTORRENT 1
#define ENABLE_BITTORRENT 1
#define CONFIG_BOOKMARKS 1
#define ENABLE_BOOKMARKS 1
#define ENABLE_BONJOUR 0
#define ENABLE_BSPATCH 0
#define ENABLE_BUGHUNT 0
#define ENABLE_CEDAR 0
#define ENABLE_COMMONCRYPTO 0
#define ENABLE_CONNMAN 0
#define CONFIG_DVD 1
#define ENABLE_DVD 1
#define CONFIG_EMU_THREAD_SPECIFICS 1
#define ENABLE_EMU_THREAD_SPECIFICS 1
#define ENABLE_FSEVENTS 0
#define CONFIG_FTPCLIENT 1
#define ENABLE_FTPCLIENT 1
#define CONFIG_FTPSERVER 1
#define ENABLE_FTPSERVER 1
#define CONFIG_GLW 1
#define ENABLE_GLW 1
#define ENABLE_GLW_BACKEND_GX 0
#define ENABLE_GLW_BACKEND_OPENGL 0
#define ENABLE_GLW_BACKEND_OPENGL_ES 0
#define CONFIG_GLW_BACKEND_RSX 1
#define ENABLE_GLW_BACKEND_RSX 1
#define ENABLE_GLW_FRONTEND_COCOA 0
#define CONFIG_GLW_FRONTEND_PS3 1
#define ENABLE_GLW_FRONTEND_PS3 1
#define ENABLE_GLW_FRONTEND_WII 0
#define ENABLE_GLW_FRONTEND_X11 0
#define ENABLE_GLW_REC 0
#define CONFIG_GLW_SETTINGS 1
#define ENABLE_GLW_SETTINGS 1
#define ENABLE_GU 0
#define CONFIG_GUMBO 1
#define ENABLE_GUMBO 1
#define CONFIG_HLS 1
#define ENABLE_HLS 1
#define CONFIG_HTSP 1
#define ENABLE_HTSP 1
#define CONFIG_HTTPSERVER 1
#define ENABLE_HTTPSERVER 1
#define CONFIG_ICECAST 1
#define ENABLE_ICECAST 1
#define ENABLE_INOTIFY 0
#define CONFIG_KVSTORE 1
#define ENABLE_KVSTORE 1
#define ENABLE_LIBASOUND 0
#define CONFIG_LIBAV 1
#define ENABLE_LIBAV 1
#define ENABLE_LIBAV_ATTACHMENT_POINTER 0
#define ENABLE_LIBCEC 0
#define ENABLE_LIBFONTCONFIG 0
#define CONFIG_LIBFREETYPE 1
#define ENABLE_LIBFREETYPE 1
#define ENABLE_LIBJPEG 0
#define CONFIG_LIBNTFS 1
#define ENABLE_LIBNTFS 1
#define ENABLE_LIBOGC 0
#define ENABLE_LIBPTHREAD 0
#define ENABLE_LIBPULSE 0
#define CONFIG_LIBRTMP 1
#define ENABLE_LIBRTMP 1
#define ENABLE_LIBX11 0
#define ENABLE_LIBXEXT 0
#define ENABLE_LIBXRANDR 0
#define ENABLE_LIBXSS 0
#define ENABLE_LIBXV 0
#define ENABLE_LIBXXF86VM 0
#define ENABLE_LIRC 0
#define ENABLE_LOCATEDB 0
#define CONFIG_MEDIA_SETTINGS 1
#define ENABLE_MEDIA_SETTINGS 1
#define CONFIG_METADATA 1
#define ENABLE_METADATA 1
#define CONFIG_NATIVESMB 1
#define ENABLE_NATIVESMB 1
#define CONFIG_NETLOG 1
#define ENABLE_NETLOG 1
#define ENABLE_NVCTRL 0
#define ENABLE_OPENSSL 0
#define CONFIG_PLAYQUEUE 1
#define ENABLE_PLAYQUEUE 1
#define CONFIG_PLUGINS 1
#define ENABLE_PLUGINS 1
#define CONFIG_POLARSSL 1
#define ENABLE_POLARSSL 1
#define CONFIG_RAR 1
#define ENABLE_RAR 1
#define ENABLE_REALPATH 0
#define ENABLE_RELEASE 0
#define ENABLE_SPOTLIGHT 0
#define CONFIG_SQLITE 1
#define ENABLE_SQLITE 1
#define CONFIG_SQLITE_INTERNAL 1
#define ENABLE_SQLITE_INTERNAL 1
#define CONFIG_SQLITE_LOCKING 1
#define ENABLE_SQLITE_LOCKING 1
#define CONFIG_SQLITE_VFS 1
#define ENABLE_SQLITE_VFS 1
#define ENABLE_STDIN 0
#define CONFIG_STPP 1
#define ENABLE_STPP 1
#define ENABLE_TIMEGM 0
#define CONFIG_TLSF 1
#define ENABLE_TLSF 1

/* Defunct upgrade and telemetry services permanently disabled */
#define CONFIG_UPGRADE 0
#define ENABLE_UPGRADE 0
#define CONFIG_USAGEREPORT 0
#define ENABLE_USAGEREPORT 0

#define CONFIG_UPNP 1
#define ENABLE_UPNP 1
#define ENABLE_VALGRIND 0
#define ENABLE_VDPAU 0
#define ENABLE_WEBKIT 0
#define ENABLE_WEBPOPUP 0
#define ENABLE_ZLIB 0
#define ENABLE_VMIR 0

